name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    name: Build (JDK ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['17', '21']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis relevancy

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run static analysis checks
        run: ./gradlew detekt ktlintCheck diktatCheck spotlessCheck --build-cache --no-daemon --stacktrace

      - name: Build with Gradle and test
        run: ./gradlew build --build-cache --no-daemon --stacktrace


      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 100

      - name: Generate Kover Test Coverage Xml Report
        run: ./gradlew koverXmlReport

      - name: Generate Jacoco Test Coverage Xml Report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports/jacoco/
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./build/reports/jacoco/test/jacocoTestReport.xml
